// Generated by build/write_buildflag_header.py
// From "//base/allocator:buildflags"

#ifndef BASE_ALLOCATOR_BUILDFLAGS_H_
#define BASE_ALLOCATOR_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_USE_ALLOCATOR_SHIM() (1)

#endif  // BASE_ALLOCATOR_BUILDFLAGS_H_